-- MySQL Script generated by MySQL Workbench
-- Tue Oct 19 18:57:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Keluarga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Keluarga` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Keluarga` (
  `id` INT NOT NULL,
  `nama` VARCHAR(255) NOT NULL,
  `kelamin` VARCHAR(255) NOT NULL,
  `anakdari` INT NULL,
  `cucudari` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Keluarga_Keluarga_idx` (`anakdari` ASC) VISIBLE,
  INDEX `fk_Keluarga_Keluarga1_idx` (`cucudari` ASC) VISIBLE,
  CONSTRAINT `fk_Keluarga_Keluarga`
    FOREIGN KEY (`anakdari`)
    REFERENCES `mydb`.`Keluarga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Keluarga_Keluarga1`
    FOREIGN KEY (`cucudari`)
    REFERENCES `mydb`.`Keluarga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
